export const IMAGES = {
  logo: "/CrushSVG-logo.svg",
  drag: "/Drag.svg",
  uploadImage: "/Upload image.svg",
  agencies: "/agencies.svg",
  designers: "/designers.svg",
  dropdown: "/dropdown.svg",
  exportIcon: "/export-icon.svg",
  downloadImage: "/download (2).svg",
  facebookLogin: "/facebook-login.svg",
  facebook: "/facebook.svg",
  file: "/file.svg",
  githubLogin: "/github-loign.svg",
  globe: "/globe.svg",
  google: "/google.svg",
  heroImage: "/image (6).png",
  instagram: "/instagram.svg",
  lock: "/lock.svg",
  marketing: "/marketing.svg",
  messageFilled: "/message-filled.svg",
  message: "/message.svg",
  profile: "/profile.svg",
  time: "/time.svg",
  twitterLogin: "/twitter-login.svg",
  linkedin: "/linkedin.svg",
  verification: "/verification.svg",
  emailVerification: "/message-filled.svg",
  window: "/window.svg",
} as const;
