export const IMAGES = {
    logo: "/crushsvg.webp",
    drag: "/drag.webp",
    uploadImage: "/upload.svg",
    agencies: "/agencies.webp",
    designers: "/designers.webp",
    dropdown: "/dropdown.webp",
    exportIcon: "/export-icon.webp",
    downloadImage: "/download-image.webp",
    facebook: "/facebook.svg",
    file: "/file.webp",
    globe: "/globe.webp",
    google: "/google.svg",
    instagram: "/instagram.svg",
    lock: "/lock.svg",
    marketing: "/marketing.webp",
    messageFilled: "/message-filled.webp",
    message: "/message.webp",
    profile: "/profile.webp",
    time: "/time.webp",
    linkedin: "/linkedin.svg",
    verification: "/verification.webp",
    emailVerification: "/message-filled.webp",
} as const;
