export const IMAGES = {
    logo: "/crushsvg.webp",
    drag: "/drag.webp",
    uploadImage: "/upload.svg",
    agencies: "/agencies.svg",
    designers: "/designers.svg",
    dropdown: "/dropdown.webp",
    exportIcon: "/export-icon.webp",
    downloadImage: "/download-image.svg",
    facebook: "/facebook.svg",
    file: "/file.webp",
    globe: "/globe.webp",
    google: "/google.svg",
    instagram: "/instagram.svg",
    lock: "/lock.svg",
    marketing: "/marketing.svg",
    messageFilled: "/message-filled.svg",
    message: "/message.svg",
    profile: "/profile.webp",
    time: "/time.webp",
    linkedin: "/linkedin.svg",
    verification: "/verification.webp",
    emailVerification: "/message-filled.svg",
} as const;
 