export const BRAND = {
  primary: "#D94A1E",
  primaryHover: "#C03D14",
  primaryLight: "#FFF0E9",
  accent: "#FF9A3D",
  bg: "#FFFFFF",
  bgSubtle: "#FFFCFA",
  text: "#353A3E",
  textBody: "#4B5563",
  textMuted: "#64748B",
  border: "#F2EDE8",
  success: "#22C55E",
  error: "#EF4444",
  fontFamily: "'Afacad', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
  fontDisplay: "'Bricolage Grotesque', 'Afacad', -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif",
  radius: "12px",
  radiusPill: "50px",
  appName: "CrushSVG",
  appUrl: process.env.APP_URL ?? "https://crushsvg.net",
} as const;